{
	"version": 1640860179,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/set3_background-sheet0.png",
		"images/set3_tiles-sheet0.png",
		"images/set3_hills-sheet0.png",
		"images/tiledbackground.png",
		"images/tiledbackground2.png",
		"images/playerred-sheet0.png",
		"images/playerred-sheet1.png",
		"images/tilegreen_-sheet0.png",
		"images/tilegreen_-sheet1.png",
		"images/tilegreen_2-sheet0.png",
		"images/tilegreen_3-sheet0.png",
		"images/tilegreen_4-sheet0.png",
		"images/enemyfloating_-sheet0.png",
		"images/enemyflying_-sheet0.png",
		"images/enemywalking_-sheet0.png",
		"images/enemywalking_-sheet1.png",
		"images/enemywalking_-sheet2.png",
		"images/tilegreen_5-sheet0.png",
		"images/tilegreen_6-sheet0.png",
		"images/tilegreen_7-sheet0.png",
		"images/tilegreen_8-sheet0.png",
		"images/enemyswimming_-sheet0.png",
		"images/enemyswimming_-sheet1.png",
		"images/enemyswimming_-sheet2.png",
		"images/bluegem-sheet0.png",
		"images/gems-sheet0.png",
		"images/spritefont.png",
		"images/hudheart_full-sheet0.png",
		"images/bonus-sheet0.png",
		"images/window-sheet0.png",
		"images/complete-sheet0.png",
		"images/btnrestart-sheet0.png",
		"images/tiledbackground3.png",
		"images/flaggreen_up-sheet0.png",
		"images/flatdark-sheet0.png",
		"images/flatdark2-sheet0.png",
		"images/flatdark3-sheet0.png",
		"images/btnsound-sheet0.png",
		"images/btnsound-sheet1.png",
		"images/btnmusic-sheet0.png",
		"images/btnmusic-sheet1.png",
		"images/btnhome-sheet0.png",
		"images/btnhome-sheet1.png",
		"images/btnexit-sheet0.png",
		"images/btnexit-sheet1.png",
		"images/btnsetting-sheet0.png",
		"images/btnsetting-sheet1.png",
		"images/play-sheet0.png",
		"images/backgroundmenu-sheet0.png",
		"images/platformerseriesinline-sheet0.png",
		"images/oie_transparent-sheet0.png",
		"images/enemyflying_2-sheet0.png",
		"images/enemyswimming_2-sheet0.png",
		"images/enemyspikey_-sheet0.png",
		"images/plantgreen_-sheet0.png",
		"images/plantgreen_2-sheet0.png",
		"images/planttop_yellow-sheet0.png",
		"images/plantgreen_3-sheet0.png",
		"images/oie_transparent2-sheet0.png",
		"images/oie_transparent3-sheet0.png",
		"images/oie_transparent4-sheet0.png",
		"media/click.m4a",
		"media/click.ogg",
		"media/collect gem.m4a",
		"media/collect gem.ogg",
		"media/enemyhit.m4a",
		"media/enemyhit.ogg",
		"media/hit.m4a",
		"media/hit.ogg",
		"media/jingle lose.m4a",
		"media/jingle lose.ogg",
		"media/jingle win.m4a",
		"media/jingle win.ogg",
		"media/mattoglseby - 1.m4a",
		"media/mattoglseby - 1.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}